version = 3

[palette]
  background = '#0f1417'
  error = '#ff5945'
  foreground = '#dfe3e7'
  outline = '#8b9297'
  primary = '#90cef4'
  secondary = '#b6c9d8'
  shadow = '#000000'
  surface = '#0f1417'
  surface_bright = '#353a3d'
  tertiary = '#cbc1e9'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ''
    foreground = 'p:foreground'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .PWD }} '
    foreground = 'p:primary'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'agnoster'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = '#FF4F00'
    type = 'rust'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = '#100e23'
    background = '#906cff'
    type = 'python'
    style = 'plain'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' git: {{ .HEAD }} '
    foreground = 'p:secondary'
    type = 'git'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = 'p:primary'
    type = 'time'
    style = 'plain'
