"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
style = "plain"
template = "\uF303"
type = "os"

[[blocks.segments]]
foreground = "#F5F5F5"
style = "plain"
text = "&#xf38d;"
type = "text"

[[blocks.segments]]
foreground = "#B80101"
style = "plain"
template = " {{ .PWD}} "
type = "path"

[blocks.segments.properties]
style = "agnoster"

[[blocks.segments]]
type = "rust"
foreground = "#FF4F00"
template = " {{ .Full }} "

[[blocks.segments]]
type = "python3"
foreground = "#100e23"
background = "#906cff"
template = "  {{ .Full }} "

# right prompt
[[blocks]]
alignment = "right"
type = "rprompt"

[[blocks.segments]]
foreground = "#B80101"
style = "plain"
template = " <#F5F5F5>git:</>{{ .HEAD }} "
type = "git"

# time
[[blocks.segments]]
style = "plain"
template = " {{ .CurrentDate | date .Format }} "
type = "time"


