[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [ "img", "-t", "outer", "--transition-duration", "1.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest",]
set = true

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/dotfiles/.config/kitty/themes/colors.conf"

[templates.oh-my-posh]
input_path = "~/.config/matugen/templates/oh-my-posh.toml"
output_path = "~/.config/ompsh/theme.toml"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.orange]
color = "#FF4F00"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#00AAFF"
blend = true

[config.custom_colors.magenta]
color = "#9141ac"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.gray]
color = "#333333"
blend = true

[config.custom_colors.pastel_blue]
color = "#99c1f1"
blend = true

[config.custom_colors.pastel_orange]
color = "#ffa348"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[config.custom_colors.pastel_green]
color = "#8ff0a4"
blend = true

[config.custom_colors.pastel_red]
color = "#f66151"
blend = true

[config.custom_colors.pastel_magenta]
color = "#dc8add"
blend = true

[config.custom_colors.pastel_mint_green]
color = "#93ddc2"
blend = true


