[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [
    "img",
    "-t",
    "grow",
    "--transition-duration",
    "4",
    "--transition-step",
    "255",
    "--transition-fps",
    "90",
  
]
set = true

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/dotfiles/.config/kitty/themes/colors.conf"

[templates.oh-my-posh]
input_path = "./templates/oh-my-posh.toml"
output_path = "~/.config/ompsh/theme.toml"

[templates.yazi]
input_path = './templates/yazi-colors.toml'
output_path = '~/dotfiles/.config/yazi/theme.toml'

[templates.quickshell-colors]
input_path = "./templates/quickshell-colors.js"
output_path = "~/dotfiles/.config/quickshell/colors.js"

[templates.spicetify-colors]
input_path = "./templates/spicetify-colors.ini"
output_path = "../spicetify/Themes/Dribbblish/color.ini"
post_hook = "spicetify apply" 

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.local/share/themes/Orchis-Dark/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.local/share/themes/Orchis-Dark/gtk-4.0/colors.css'

[templates.svg]
input_path = "./templates/svg-colors.svg"
output_path = "../quickshell/icons/battery/battery-vertical_full.svg"

[templates.cava-colors]
input_path = "./templates/cava-colors"
output_path = "../cava/config"
post_hook = "pkill -USR1 cava"
[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.orange]
color = "#FF4F00"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true



[config.custom_colors.blue]
color = "#00AAFF"
blend = true

[config.custom_colors.magenta]
color = "#9141ac"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.gray]
color = "#333333"
blend = true

[config.custom_colors.pastel_blue]
color = "#99c1f1"
blend = true

[config.custom_colors.pastel_orange]
color = "#ffa348"
blend = true

[config.custom_colors.white]
color = "#FFFFFFFF"
blend = false

[config.custom_colors.pastel_green]
color = "#8ff0a4FF"
blend = true

[config.custom_colors.pastel_red]
color = "#f66151"
blend = true

[config.custom_colors.pastel_magenta]
color = "#dc8add"
blend = true

[config.custom_colors.pastel_mint_green]
color = "#93ddc2"
blend = true
