# Custom Starship Configuration
# Save as ~/.config/starship.toml

add_newline = false
command_timeout = 1000

# Main prompt format - two lines for clean separation
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$nodejs\
$python\
$rust\
$golang\
$java\
$php\
$ruby\
$fill\
$cmd_duration\
$jobs\
$battery\
$time\
$line_break\
$character"""

# Right-side prompt for additional info
right_format = """$status"""

# Username - only show when SSH or root
[username]
format = "[$user]($style)@"
style_user = "bold cyan"
style_root = "bold red"
show_always = false

# Hostname - only show when SSH
[hostname]
format = "[$hostname]($style) "
style = "bold green"
ssh_only = true

# Directory with custom styling
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold blue"
truncation_length = 4
truncation_symbol = "…/"
read_only = " 🔒"
read_only_style = "red"

# Git branch with icon
[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold purple"

# Git commit info
[git_commit]
commit_hash_length = 8
format = "[($hash$tag)]($style) "
style = "green"

# Git status with detailed symbols
[git_status]
format = "([[$all_status$ahead_behind]]($style) )"
style = "red"
conflicted = "⚡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

# Git state (merge, rebase, etc.)
[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "
style = "bright-black"

# Fill the space between left and right
[fill]
symbol = "─"
style = "bright-black"

# Command duration
[cmd_duration]
min_time = 2000
format = " [$duration]($style)"
style = "yellow"

# Background jobs
[jobs]
format = " [$symbol$number]($style)"
symbol = "✦"
style = "bold blue"

# Battery status
[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"
format = " [$symbol$percentage]($style)"

[[battery.display]]
threshold = 30
style = "bold red"

[[battery.display]]
threshold = 60
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

# Time display
[time]
disabled = false
format = " [$time]($style)"
time_format = "%H:%M"
style = "bright-black"

# Command status
[status]
format = "[$symbol$status]($style) "
symbol = "✖"
success_symbol = ""
not_executable_symbol = "🚫"
not_found_symbol = "🔍"
sigint_symbol = "🧱"
signal_symbol = "⚡"
style = "bold red"
disabled = false

# Prompt character
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

# Docker context
[docker_context]
format = " [$symbol$context]($style)"
symbol = "🐳 "
style = "blue"

# Package version
[package]
format = " [$symbol$version]($style)"
symbol = "📦 "
style = "208"

# Language versions
[nodejs]
format = " [$symbol($version )]($style)"
symbol = " "
style = "bold green"

[python]
format = " [$symbol$pyenv_prefix($version )(($virtualenv) )]($style)"
symbol = " "
style = "bold yellow"

[rust]
format = " [$symbol($version )]($style)"
symbol = " "
style = "bold red"

[golang]
format = " [$symbol($version )]($style)"
symbol = " "
style = "bold cyan"

[java]
format = " [$symbol($version )]($style)"
symbol = " "
style = "red"

[php]
format = " [$symbol($version )]($style)"
symbol = " "
style = "147"

[ruby]
format = " [$symbol($version )]($style)"
symbol = " "
style = "bold red"

# Cloud providers
[aws]
format = " [$symbol($profile )(\\($region\\) )]($style)"
symbol = "☁️  "
style = "bold blue"

[gcloud]
format = " [$symbol$account(@$domain)(\\($region\\))]($style)"
symbol = "☁️  "
style = "bold blue"

# Kubernetes
[kubernetes]
format = " [$symbol$context( \\($namespace\\))]($style)"
symbol = "⎈ "
style = "cyan"
disabled = false

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

# Memory usage
[memory_usage]
disabled = false
threshold = 75
format = " [$symbol${ram}( | ${swap})]($style)"
symbol = "🐏 "
style = "bold dimmed white"

# Shell indicator
[shell]
disabled = false
format = " [$indicator]($style)"
fish_indicator = "🐠"
powershell_indicator = "💙"
bash_indicator = "🐧"
zsh_indicator = "⚡"
unknown_indicator = "❓"
style = "cyan bold"
